language: php

php:
  - 7.1

before_script:
  - composer update

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - if php -i |grep -qE xdebug; then ./vendor/bin/humbug; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
